/**:
  processor:
    ros__parameters:

      # For marker detection
      marker_set: 'HD19'
      marker_width: 0.115
      only_process_image_on_trigger: False

      # For multi-channel marker detection
      overlay_proximity: 30
      #merge_option_1: 'none'
      #merge_option_1: 'additive'
      #merge_option_1: 'binary'
      #merge_option_1: 'modal'
      merge_option_1: 'average'
      #merge_option_1: 'median'
      merge_option_2: 'binary'

      # For camera calibration
      dfov: 68.5 #get from camera info?
      hfov: -0.0

      # For position smoothing
      use_rolling_filter: true
      rolling_filter_len: 10 #todo: change this to 0=false

      # For rendering
      label_color_image: true
      label_depth_image: false

  calibrator:
    ros__parameters:
      calibration_config_file: 'package://stag_ros2/config/stag_markers.yaml'
      trigger_calibration_once: False
      minimum_calibration_markers: 1

  mqtt_forwarder:
    ros__parameters:
      mqtt_encoding: 'json'
      mqtt_ns: 'stag_ros2'
