# Used for localising the tf frame of the camera
markers:
  - id: 0
    hamming: 'HD19'
    radius: 0.115 #m
    pose:
      position:
          x: 0.0
          y: 0.0
          z: 0.0
      orientation:
          w: 0.0
          x: 1.0
          y: 0.0
          z: 0.0
  - id: 1
    hamming: 'HD19'
    radius: 0.115 #m
    pose:
      position:
          x: 0.144
          y: 0.0
          z: 0.0
      orientation:
          w: 0.0
          x: 1.0
          y: 0.0
          z: 0.0
